vich_uploader:
  db_driver: orm

  mappings:
    dogs:
      uri_prefix: /img/dogs
      upload_destination: "%kernel.project_dir%/public/img/dogs"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
